### ISSUE TITLE
Optional expiration date/time on keys

### ISSUE THREAD

**Issue by sulsay** [sulsay/torn-proxy#6]
zim312 [suggested](https://www.torn.com/forums.php#/p=threads&f=63&t=16178384&b=0&a=0&start=0&to=20649029) we add expiration dates to keys.

Paired with granular permissions, it could create a market for "leased" API keys used for scraping or other things.

Though not a priority right now, it _could_ entice people to start using and supporting proxy keys.

**Comment by waterock** [comment]
Closing because project is dead
