### ISSUE TITLE
Permissions per key

### ISSUE THREAD

**Issue by sulsay** [sulsay/torn-proxy#7]
The proxy's added value compared to torn's native API largely depends on its extra features. A key feature is for users to be able to set permissions on a per-key basis.

### User interface
We need to make it easy for users to set their permissions per key. A simple interface with checkboxes might suffice at first.

### Granularity
My initial idea was to separate public-data calls from private-data ones. But it might be easier to just let the user toggle each selection per endpoint.

### Torn / tornstats
The proxy support tornstats too. So keep that in mind when designing both the back-end and the user interface. It's pivotal that users can fully enable/disable an entire application, with "application" in this context meaning torn/tornstats.

### Dealing with requests to denied endpoints
Instead of omitting selections in the response to which a key has no access, it's probably easier for everyone to return some error code + message when that happens. For example, a consumer app requests `/users/?selections=basic,money`, but the key has no access to `money`. Instead of returning `basic` but omitting `money`, we should return no data at all but an error instead.

**Comment by realname0000** [comment]
What about proxy keys to query faction (rather than user data).  Maybe these should be wholly different keys (or include as part of the permissioning system).

**Comment by Fogest** [comment]
I would like to just chime in on what @realname0000 said. I think their suggestion would actually take this to the next level. It would be amazing if faction members with API access could generate a key to give to faction members which has certain areas this API key could access. Right now the faction API access permission can often give members permission to too much faction data. 

For example in TornTools they have some features like being able to view your OC timer right on the sidebar. You could have features like OC timers, personal faction vault amounts, etc... all able to grab from the faction API through a proxy key without having to give a user full permissions to get all of the faction API. 

I think this has **huge** potential and should be heavily considered.

**Comment by waterock** [comment]
Sounds good to me, I'll leave this issue open for now (and eventually make a new issue for adding faction permissions).

**Comment by waterock** [comment]
Closing because project is dead
